import type { SearchEntry } from "./navigation";

export const searchContent: SearchEntry[] = [
  {
    title: "Points per purchase",
    href: "/docs/loyalty/earn-rules",
    section: "Loyalty Program",
    description: "Configure how many points customers earn per dollar spent",
  },
  {
    title: "Auto-approve reviews",
    href: "/docs/settings/review-settings",
    section: "Settings",
    description: "Set rating threshold for automatic review approval",
  },
  {
    title: "Blacklisted words",
    href: "/docs/settings/review-settings",
    section: "Settings",
    description: "Block reviews containing specific words",
  },
  {
    title: "CSV import Judge.me",
    href: "/docs/reviews/importing",
    section: "Reviews",
    description: "Import reviews from Judge.me via CSV upload",
  },
  {
    title: "CSV import Loox",
    href: "/docs/reviews/importing",
    section: "Reviews",
    description: "Import reviews from Loox via CSV upload",
  },
  {
    title: "Discount codes",
    href: "/docs/loyalty/rewards",
    section: "Loyalty Program",
    description: "How reward redemptions create Shopify discount codes",
  },
  {
    title: "Free shipping reward",
    href: "/docs/loyalty/rewards",
    section: "Loyalty Program",
    description: "Create free shipping rewards for point redemption",
  },
  {
    title: "Percentage off reward",
    href: "/docs/loyalty/rewards",
    section: "Loyalty Program",
    description: "Create percentage-based discount rewards",
  },
  {
    title: "Fixed amount reward",
    href: "/docs/loyalty/rewards",
    section: "Loyalty Program",
    description: "Create fixed dollar amount discount rewards",
  },
  {
    title: "Points expiry",
    href: "/docs/settings/general",
    section: "Settings",
    description: "Configure when earned points expire",
  },
  {
    title: "Custom points name",
    href: "/docs/settings/general",
    section: "Settings",
    description: "Rename points to Stars, Gems, or any custom name",
  },
  {
    title: "Review request emails",
    href: "/docs/reviews/review-requests",
    section: "Reviews",
    description: "Automatic post-purchase review request emails",
  },
  {
    title: "Reminder emails",
    href: "/docs/reviews/review-requests",
    section: "Reviews",
    description: "Follow-up reminders for review requests",
  },
  {
    title: "Email templates",
    href: "/docs/settings/email",
    section: "Settings",
    description: "Customize review request email subject and body",
  },
  {
    title: "Referral program",
    href: "/docs/loyalty/referrals",
    section: "Loyalty Program",
    description: "Enable refer-a-friend with points for both parties",
  },
  {
    title: "VIP tiers",
    href: "/docs/loyalty/vip-tiers",
    section: "Loyalty Program",
    description: "Member, Silver, Gold tier system with multipliers",
  },
  {
    title: "Points multiplier",
    href: "/docs/loyalty/vip-tiers",
    section: "Loyalty Program",
    description: "Higher tiers earn bonus points via multiplier",
  },
  {
    title: "Checkout extension",
    href: "/docs/widgets/checkout-widget",
    section: "Widgets",
    description: "Redeem points at checkout with the Shopify checkout extension",
  },
  {
    title: "Theme app blocks",
    href: "/docs/widgets/overview",
    section: "Widgets",
    description: "All storefront app blocks available for Online Store 2.0",
  },
  {
    title: "JSON-LD structured data",
    href: "/docs/reviews/seo",
    section: "Reviews",
    description: "Review rich snippets for Google search results",
  },
  {
    title: "Shopify Flow trigger",
    href: "/docs/reviews/shopify-flow",
    section: "Reviews",
    description: "Trigger Flow automations when reviews are approved",
  },
  {
    title: "Customer account page",
    href: "/docs/widgets/customer-account",
    section: "Widgets",
    description: "Loyalty page in the customer account portal",
  },
  {
    title: "Billing plans pricing",
    href: "/docs/settings/billing",
    section: "Settings",
    description: "Free, Essential ($29/mo), Growth ($99/mo), and Studio ($299/mo) plans",
  },
  {
    title: "Webhook events",
    href: "/docs/advanced/webhooks",
    section: "Advanced",
    description: "Order, customer, and app lifecycle webhooks",
  },
  {
    title: "Widget trigger button",
    href: "/docs/settings/trigger-button",
    section: "Settings",
    description: "Customize the floating button that opens the loyalty launcher",
  },
  {
    title: "Launcher header image",
    href: "/docs/settings/widget-customization",
    section: "Settings",
    description: "Upload custom header image for the loyalty widget",
  },
  {
    title: "Remove branding",
    href: "/docs/settings/general",
    section: "Settings",
    description: "Remove Powered by PerkStack from widgets (Growth+)",
  },
  {
    title: "App pixel tracking",
    href: "/docs/advanced/web-pixel",
    section: "Advanced",
    description: "Checkout tracking for order completion events",
  },
  {
    title: "Admin customer blocks",
    href: "/docs/advanced/admin-extensions",
    section: "Advanced",
    description: "Customer reviews and loyalty blocks in Shopify admin",
  },
  {
    title: "Review status lifecycle",
    href: "/docs/advanced/status-reference",
    section: "Advanced",
    description: "Pending, approved, rejected, spam status transitions",
  },
  {
    title: "Helpful votes",
    href: "/docs/reviews/overview",
    section: "Reviews",
    description: "Customers can mark reviews as helpful",
  },
  {
    title: "Featured reviews",
    href: "/docs/reviews/moderation",
    section: "Reviews",
    description: "Pin important reviews as featured across your store",
  },
  {
    title: "Verified purchase badge",
    href: "/docs/reviews/overview",
    section: "Reviews",
    description: "Reviews linked to actual orders show verified badge",
  },
  {
    title: "Freeze customer loyalty",
    href: "/docs/customers/freeze",
    section: "Customers",
    description: "Temporarily freeze a customer's loyalty participation",
  },
  {
    title: "Birthday rewards setup",
    href: "/docs/loyalty/birthday-rewards",
    section: "Loyalty Program",
    description: "Award points on customer birthdays automatically",
  },
  {
    title: "Social share points",
    href: "/docs/loyalty/social-sharing",
    section: "Loyalty Program",
    description: "Reward points for sharing products on social media",
  },
];
